    @num=(1..15);
    print "@num\n";
    print"splice function:\n";
    splice(@num,5,5,1..10);
    print "@num\n";
    $string="my-name-is-rohan";
    print "$string\n";
    print"this is split function:\n";
    @yo=split('-',$string);
    print "$yo[0]\n";
    print "$yo[1]\n";
    print "$yo[2]\n";
    print "$yo[3]\n";
    print "this is join:\n";
    $yo_join=join('-',@yo);
    print "$yo_join\n";
    @color1=("black","green","white");
    print "array1= @color1\n";
    @color2=("blue","red","grey");
    print "array2=@color2\n";
    print"merge array1 and arry2:\n";
    @col=(@color1,@color2);
    print "@col\n";
    print "sorting..\n";
    @unsorted=(1000,100,10,1000000,10000);
    print "unsorted array:@unsorted\n";
   @sorted=sort(@unsorted);
   print "sorted array:@sorted\n";


